server:
    port: 8280
spring:
    application:
        name: CouponBookConfigService
    cloud:
        config:
            server:
                git:
                    password: Bill@2019
                    uri: https://github.com/YunchuWang/CouponBookConfigService
                    username: peterstone2017
            profile: dev